### ISSUE TITLE
weird error during intunewin package creation

### ISSUE THREAD

**Issue by mdurini-swisscom** [SaadKhamis/IntuneWinAppUtilGUI#2]
Hi, I'm trying to create a package with konica minolta drivers and PS1 file as setup file. I'm getting this error

INFO   Validating parameters
INFO   Validated parameters within 2 milliseconds
INFO   Removing temporary files
ERROR  System.IO.IOException: The handle is invalid.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at Microsoft.Management.Service.IntuneWinAppUtil.LogUtil.PrintProgress(AppContext context)
   at Microsoft.Management.Service.IntuneWinAppUtil.PackageUtil.CreatePackage(String folder, String setupFile, String outputFolder, String catalogFolder)
   at Microsoft.Management.Service.IntuneWinAppUtil.Program.Main(String[] args)

If i try to run intunwinapputil as you are triyng to do from your app, everything is working.

**Comment by SaadKhamis** [comment]
Hello.
Sorry, the issue is not clear to me.
Does my utility successfully create the package?

**Comment by gitnewcomer** [comment]
> Hello. Sorry, the issue is not clear to me. Does my utility successfully create the package?

Hi, I have the same issue as @mdurini-swisscom, if I hit "Execute" on your utility, it shows the same error on utility output.
If I copy the command generated on your utility and execute it on a command line shell, the package will be created, so there is something wrong invoking the command inside your utility.
It could be related to the console output being redirected: https://developercommunity.visualstudio.com/t/vs2019-consoleclear-throws-an-exception-when-calle/526928

I'm using IntuneWinAppUtil.exe v1.8.5.0...

Are you planning to open source your utility? Maybe someone could help improve it... :)

**Comment by SaadKhamis** [comment]
> > Hello. Sorry, the issue is not clear to me. Does my utility successfully create the package?
> 
> Hi, I have the same issue as @mdurini-swisscom, if I hit "Execute" on your utility, it shows the same error on utility output. If I copy the command generated on your utility and execute it on a command line shell, the package will be created, so there is something wrong invoking the command inside your utility. It could be related to the console output being redirected: https://developercommunity.visualstudio.com/t/vs2019-consoleclear-throws-an-exception-when-calle/526928
> 
> I'm using IntuneWinAppUtil.exe v1.8.5.0...
> 
> Are you planning to open source your utility? Maybe someone could help improve it... :)

Please share the command generated. Thank you.

**Comment by gitnewcomer** [comment]
> Please share the command generated. Thank you.

This is the error I have when I use the utility (if I execute the generated command on the command line, it works):

`28.03.2024 12:43:25: Start`
`User Ctrl+Alt+x to terminate the process, if needed.`

`Command`
`C:\Apps\Microsoft\M365_Apps_Prepare_Tool\IntuneWinAppUtil.exe -q -c "C:\Apps\Microsoft\M365_Apps_Prepare_Tool\MicrosoftTeams_Remove\Source" -s "C:\Apps\Microsoft\M365_Apps_Prepare_Tool\MicrosoftTeams_Remove\Source\MicrosoftTeams_Remove.cmd" -o "C:\Apps\Microsoft\M365_Apps_Prepare_Tool\MicrosoftTeams_Remove\Package"`
`Process ID: 448`

`Output
INFO   Validating parameters
INFO   Validated parameters within 10 milliseconds
INFO   Removing temporary files
ERROR  System.IO.IOException: The handle is invalid.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at Microsoft.Management.Service.IntuneWinAppUtil.LogUtil.PrintProgress(AppContext context)
   at Microsoft.Management.Service.IntuneWinAppUtil.PackageUtil.CreatePackage(String folder, String setupFile, String outputFolder, String catalogFolder)
   at Microsoft.Management.Service.IntuneWinAppUtil.Program.Main(String[] args)`

`28.03.2024 12:43:25: End`
